library(dplyr)
library(BioCro)
new_params_final_temp <- iter5_iSp1.4_switch_TTrep_Params_fitted_to_2017_minimizing_ChiSquare
final_parameters <- new_params_final_temp[2,]
names(final_parameters) <- new_params_final_temp[1,]
result_2017 <- run_biocro(init_vals_logistic,final_parameters,yrClimate(2017),sorghum_steady_state_modules_logistic,sorghum_derivative_modules_logistic)
result_2019 <- run_biocro(init_vals_logistic,final_parameters,yrClimate(2019),sorghum_steady_state_modules_logistic,sorghum_derivative_modules_logistic)
result_2018 <- run_biocro(init_vals_logistic,final_parameters,yrClimate(2018),sorghum_steady_state_modules_logistic,sorghum_derivative_modules_logistic)


byDay_2017 <- result_2017 %>% group_by(doy) %>% summarize(meanYield = mean(Leaf)+mean(Stem),meanLAI = mean(lai))
byDay_2019 <- result_2019 %>% group_by(doy) %>% summarize(meanYield = mean(Leaf)+mean(Stem),meanLAI = mean(lai))
byDay_2018 <- result_2018 %>% group_by(doy) %>% summarize(meanYield = mean(Leaf)+mean(Stem),meanLAI = mean(lai))
View(byDay_2017)


df_yield_2017 <- inner_join(mean_var_yield_2017,actual_yield_2017,by=c('doy'))
View(df_yield_2017)
df_yield_2017 <- inner_join(df_yield_2017,byDay_2017,by=c('doy'))
df_yield_2017 <- mutate(df_yield_2017,MahalTerm = (meanYield - yield_Mg_ha)^2 / VarianceYield)
df_yield_count_2017 <- df_yield_2017 %>% count(doy)
df_yield_2017 <- df_yield_2017 %>% group_by(doy) %>% summarize(meanYield = mean(meanYield), varianceYield = mean(VarianceYield), Mahal = sqrt(sum(MahalTerm)))
df_yield_2017 <- inner_join(df_yield_count_2017,df_yield_2017,by=c('doy'))
mean_var_yield_sig_2019 <- mean_var_yield_2019
df_yield_2019 <- inner_join(mean_var_yield_sig_2019,actual_yield_2019,by=c('doy'))
df_yield_2019 <- inner_join(df_yield_2019,byDay_2019,by=c('doy'))
df_yield_2019 <- mutate(df_yield_2019,MahalTerm = (meanYield - yield_Mg_ha)^2 / VarianceYield)
df_yield_count_2019 <- df_yield_2019 %>% count(doy)
df_yield_2019 <- df_yield_2019 %>% group_by(doy) %>% summarize(meanYield = mean(meanYield), varianceYield = mean(VarianceYield), Mahal = sqrt(sum(MahalTerm)))
df_yield_2019 <- inner_join(df_yield_count_2019,df_yield_2019,by=c('doy'))
View(df_yield_2019)
df_yield <- rbind(df_yield_2019,df_yield_2017)
df_yield_2018 <- inner_join(mean_var_yield_2018,actual_yield_2018,by=c('doy'))
df_yield_2018 <- inner_join(df_yield_2018,byDay_2018,by=c('doy'))
df_yield_2018 <- mutate(df_yield_2018,MahalTerm = (meanYield - yield_Mg_ha)^2 / VarianceYield)
df_yield_count_2018 <- df_yield_2018 %>% count(doy)
df_yield_2018 <- df_yield_2018 %>% group_by(doy) %>% summarize(meanYield = mean(meanYield), varianceYield = mean(VarianceYield), Mahal = sqrt(sum(MahalTerm)))
df_yield_2018 <- inner_join(df_yield_count_2018,df_yield_2018,by=c('doy'))
df_yield <- rbind(df_yield,df_yield_2018)
df_yield <- mutate(df_yield,MahalMod = Mahal/sqrt(n))

graph_mean_var_yield <- ggplot(df_yield,aes(x=n,y=MahalMod)) + geom_point()
x11()
print(graph_mean_var_yield)

df_lai_2017 <- inner_join(mean_var_leaf_area_2017,actual_leaf_area_2017,by=c('doy'))
df_lai_2017 <- inner_join(df_lai_2017,byDay_2017,by=c('doy'))
View(df_lai_2017)
df_lai_2017 <- mutate(df_lai_2017,MahalTerm = (meanLAI - LAI)^2 / VarianceLAI)
df_lai_count_2017 <- df_lai_2017 %>% count(doy)
df_lai_2017 <- df_lai_2017 %>% group_by(doy) %>% summarize(meanLAI = mean(meanLAI), varianceLAI = mean(VarianceLAI), Mahal = sqrt(sum(MahalTerm)))
df_lai_2017 <- inner_join(df_lai_count_2017,df_lai_2017,by=c('doy'))
df_lai_2019 <- inner_join(mean_var_leaf_area_2019,actual_leaf_area_2019,by=c('doy'))
df_lai_2019 <- inner_join(df_lai_2019,byDay_2019,by=c('doy'))
df_lai_2019 <- mutate(df_lai_2019,MahalTerm = (meanLAI - LAI)^2 / VarianceLAI)
df_lai_count_2019 <- df_lai_2019 %>% count(doy)
df_lai_2019 <- df_lai_2019 %>% group_by(doy) %>% summarize(meanLAI = mean(meanLAI), varianceLAI = mean(VarianceLAI), Mahal = sqrt(sum(MahalTerm)))
df_lai_2019 <- inner_join(df_lai_count_2019,df_lai_2019,by=c('doy'))
df_lai <- rbind(df_lai_2017,df_lai_2019)
df_lai_2018 <- inner_join(mean_var_leaf_area_2018,actual_leaf_area_2018,by=c('doy'))
df_lai_2018 <- inner_join(df_lai_2018,byDay_2018,by=c('doy'))
df_lai_2018 <- mutate(df_lai_2018,MahalTerm = (meanLAI - LAI)^2 / VarianceLAI)
df_lai_count_2018 <- df_lai_2018 %>% count(doy)
df_lai_2018 <- df_lai_2018 %>% group_by(doy) %>% summarize(meanLAI = mean(meanLAI), varianceLAI = mean(VarianceLAI), Mahal = sqrt(sum(MahalTerm)))
df_lai_2018 <- inner_join(df_lai_count_2018,df_lai_2018,by=c('doy'))
df_lai <- rbind(df_lai,df_lai_2018)
df_lai <- mutate(df_lai,MahalMod = Mahal/sqrt(n))

graph_mean_var_lai <- ggplot(df_lai,aes(x=n,y=MahalMod)) + geom_point()
x11()
print(graph_mean_var_yield + graph_mean_var_lai)
